name = "PhasorNetworks"
uuid = "c32d742c-e486-48f1-8804-9f6fb4d3f42c"
authors = ["Wilkie Olin-Ammentorp"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
