#!/usr/bin/env julia
# Aggregate results/*.csv into the tidy .dat tables the manuscript figures read.
#
# The figures are TikZ/pgfplots living in ICRC-LIEP-manuscript/figures/, so the
# paper rebuilds from its own sources. This script is the only bridge: nothing
# downstream of here recomputes an experiment, and no .tex file contains a
# hand-typed number taken from a result.
#
# Numbers that appear as TEXT in a figure (a fitted boundary, a mean difference)
# are emitted as LaTeX macros into figures/data/figN_macros.tex, so those are
# generated from the CSVs too rather than transcribed by hand.
#
#   julia --project=scripts scripts/export_figure_data.jl
#
# Env: LIEP_FIGDATA to redirect the output directory.

using Pkg
function find_repo_root(start_dir::String = pwd())
    dir = start_dir
    while !(isfile(joinpath(dir, "Project.toml")) && isdir(joinpath(dir, ".git")))
        parent = dirname(dir); parent == dir && error("no repo root"); dir = parent
    end
    return dir
end
repo_root = find_repo_root(@__DIR__); cd(repo_root); Pkg.activate(joinpath(repo_root, "scripts"))

using CSV, DataFrames, Statistics, Printf, Random

const RES = joinpath(repo_root, "results")
const DAT = get(ENV, "LIEP_FIGDATA",
                joinpath(homedir(), "Documents", "ICRC-LIEP-manuscript", "figures", "data"))
mkpath(DAT)

const MACROS = Dict{String, Vector{Pair{String,String}}}()
macroset!(fig, name, val) = push!(get!(MACROS, fig, Pair{String,String}[]), name => val)

"""Write a whitespace table with a provenance comment. pgfplots skips `#` lines."""
function writedat(name::String, df::DataFrame; source::String, note::String = "")
    path = joinpath(DAT, name)
    open(path, "w") do io
        println(io, "# generated by scripts/export_figure_data.jl -- do not edit")
        println(io, "# source: ", source)
        isempty(note) || println(io, "# note: ", note)
        println(io, join(names(df), " "))
        for r in eachrow(df)
            println(io, join((v isa AbstractString ? v : @sprintf("%.6g", v) for v in r), " "))
        end
    end
    @printf("  %-28s %4d rows\n", name, nrow(df))
end

"""
Emit a closed polygon tracing hi forward then lo backward, so a band can be
drawn with a plain `\addplot[fill] table` -- no fillbetween library, and so no
change to the manuscript preamble.
"""
function writeband(name::String, x, lo, hi; source::String, note::String = "")
    bx = vcat(collect(x), reverse(collect(x)))
    by = vcat(collect(hi), reverse(collect(lo)))
    writedat(name, DataFrame(x = bx, y = by); source = source, note = note)
end

function write_macros()
    for (fig, defs) in MACROS
        path = joinpath(DAT, "$(fig)_macros.tex")
        open(path, "w") do io
            println(io, "% generated by scripts/export_figure_data.jl -- do not edit")
            for (n, v) in defs
                println(io, "\\newcommand{\\", n, "}{", v, "}")
            end
        end
        @printf("  %-28s %4d macros\n", "$(fig)_macros.tex", length(defs))
    end
end

gitrev_of(df) = "gitrev" in names(df) ? string(first(df.gitrev)) : "n/a"

# Wilson score interval. The grid has 8 draws per cell, where the normal
# approximation is not usable and runs outside [0,1] at the saturated cells.
function wilson(k, n; z = 1.96)
    p = k / n; d = 1 + z^2 / n
    c = (p + z^2 / (2n)) / d
    h = z * sqrt(p * (1 - p) / n + z^2 / (4n^2)) / d
    return (max(0.0, c - h), min(1.0, c + h))
end

# Two-parameter logistic by IRLS.
function logistic_fit(x, y; iters = 100)
    b = [0.0, 0.0]
    for _ in 1:iters
        p = 1 ./ (1 .+ exp.(-(b[1] .+ b[2] .* x)))
        w = max.(p .* (1 .- p), 1e-9); r = y .- p
        s0 = sum(w); s1 = sum(w .* x); s2 = sum(w .* x .^ 2)
        det = s0 * s2 - s1^2; abs(det) < 1e-12 && break
        db = [(s2 * sum(r) - s1 * sum(r .* x)) / det,
              (-s1 * sum(r) + s0 * sum(r .* x)) / det]
        b .+= db; maximum(abs, db) < 1e-12 && break
    end
    return b
end

println("=== exporting figure data to $DAT ===")

# =====================================================================
# kappa -- sets Figure 1's x axis
# =====================================================================
kap = CSV.read(joinpath(RES, "e7_kappa", "kappa_ddbaa3d.csv"), DataFrame)
KAPPA = median(skipmissing(kap.kappa))
@printf("kappa = %.5f  (median of %d input draws, range %.4f-%.4f)\n",
        KAPPA, nrow(kap), minimum(kap.kappa), maximum(kap.kappa))
macroset!("fig1", "FigKappa", @sprintf("%.3f", KAPPA))
macroset!("fig1", "FigKappaLo", @sprintf("%.3f", minimum(kap.kappa)))
macroset!("fig1", "FigKappaHi", @sprintf("%.3f", maximum(kap.kappa)))
macroset!("fig1", "FigKappaN", string(nrow(kap)))

# =====================================================================
# Figure 1 -- adiabatic basin
# =====================================================================
println("\nFigure 1:")
grid = CSV.read(joinpath(RES, "ep_adiabatic", "grid.csv"), DataFrame)
grid.fail = grid.cos_l1 .< 0.9
const NC_MAIN = 4

g4 = grid[grid.n_cycles .== NC_MAIN, :]
mp = combine(groupby(g4, [:eps, :omega_p]), :cos_l1 => median => :cosmed, nrow => :n)
mp.wk = mp.omega_p ./ KAPPA
sort!(mp, [:eps, :omega_p])
writedat("fig1_map.dat", select(mp, :wk, :eps, :cosmed, :omega_p);
         source = "results/ep_adiabatic/grid.csv (n_cycles=$NC_MAIN, 8 draws/cell); kappa from results/e7_kappa",
         note = "wk = omega_p / kappa; cosmed = median cos_l1 over the 8 input draws")

# Boundary: logistic in log10(omega_p) over eps >= 0.01. The eps dependence is
# NOT monotone -- eps >= 0.01 behaves identically while eps = 0.003 fails from
# below -- so a two-variable fit would impose a trend the data contradicts.
sub = grid[grid.eps .>= 0.01, :]
b = logistic_fit(log10.(Float64.(sub.omega_p)), Float64.(sub.fail))
wstar(p) = 10.0^((log(p / (1 - p)) - b[1]) / b[2])
bnd = DataFrame(p = [0.1, 0.5, 0.9],
                wk = [wstar(p) / KAPPA for p in (0.1, 0.5, 0.9)],
                omega_p = [wstar(p) for p in (0.1, 0.5, 0.9)])
writedat("fig1_bound.dat", bnd;
         source = "logistic fit of (cos_l1 < 0.9) on log10(omega_p); $(nrow(sub)) runs with eps >= 0.01",
         note = "p = failure probability; slope $(round(b[2], digits = 2)) per decade")
macroset!("fig1", "FigBoundWk", @sprintf("%.2f", wstar(0.5) / KAPPA))
macroset!("fig1", "FigBoundWkC", @sprintf("%.5f", wstar(0.5) / KAPPA))
macroset!("fig1", "FigBoundWkLo", @sprintf("%.5f", wstar(0.1) / KAPPA))
macroset!("fig1", "FigBoundWkHi", @sprintf("%.5f", wstar(0.9) / KAPPA))
macroset!("fig1", "FigBoundWp", @sprintf("%.3f", wstar(0.5)))
macroset!("fig1", "FigBoundSlope", @sprintf("%.1f", b[2]))
macroset!("fig1", "FigBoundN", string(nrow(sub)))

# Failure-rate strip, sharing the map's x axis.
function failband(df)
    m = combine(groupby(df, :omega_p), :fail => sum => :k, nrow => :n)
    sort!(m, :omega_p)
    lo = [wilson(r.k, r.n)[1] for r in eachrow(m)]
    hi = [wilson(r.k, r.n)[2] for r in eachrow(m)]
    DataFrame(wk = m.omega_p ./ KAPPA, rate = m.k ./ m.n, lo = lo, hi = hi)
end
fh = failband(grid[grid.eps .>= 0.01, :])
rename!(fh, :rate => :ratehi, :lo => :lohi, :hi => :hihi)
fl = failband(grid[grid.eps .< 0.01, :])
rename!(fl, :rate => :ratelo, :lo => :lolo, :hi => :hilo)
writeband("fig1_fail_bandhi.dat", fh.wk, fh.lohi, fh.hihi;
          source = "results/ep_adiabatic/grid.csv, eps >= 0.01", note = "Wilson 95%")
writeband("fig1_fail_bandlo.dat", fl.wk, fl.lolo, fl.hilo;
          source = "results/ep_adiabatic/grid.csv, eps = 0.003", note = "Wilson 95%")
writedat("fig1_fail.dat", innerjoin(fh, fl, on = :wk);
         source = "results/ep_adiabatic/grid.csv, all n_cycles",
         note = "hi = pooled eps >= 0.01; lo = eps = 0.003; Wilson 95% bounds")

# Training curves at the called-out points.
e6 = CSV.read(joinpath(RES, "e6_basin_training", "e6_basin_ddbaa3d.csv"), DataFrame)
pts = DataFrame(label = String[], wk = Float64[], eps = Float64[],
                acc = Float64[], w1 = Float64[], cosmed = Float64[])
for p in sort(unique(e6.point))
    s = e6[e6.point .== p, :]
    c = combine(groupby(s, :epoch), :loss => median => :med,
                :loss => minimum => :lo, :loss => maximum => :hi)
    sort!(c, :epoch)
    writedat("fig1_loss_$(p).dat", c;
             source = "results/e6_basin_training/e6_basin_$(gitrev_of(e6)).csv, point $p, 3 seeds",
             note = "med = median loss across seeds; lo/hi = min/max")
    lastep = maximum(s.epoch)
    e, w = first(s.eps), first(s.omega_p)
    cell = g4[(g4.eps .≈ e) .& (g4.omega_p .≈ w), :cos_l1]
    acc = median(s[s.epoch .== lastep, :test_acc])
    w1  = median(s[s.epoch .== lastep, :w1_norm])
    push!(pts, (p, w / KAPPA, e, acc, w1, isempty(cell) ? NaN : median(cell)))
    macroset!("fig1", "FigAcc$p", @sprintf("%.3f", acc))
    macroset!("fig1", "FigWone$p", @sprintf("%.0f", w1))
    macroset!("fig1", "FigWk$p", @sprintf("%.5f", w / KAPPA))
    macroset!("fig1", "FigEps$p", @sprintf("%.5f", e))
    writeband("fig1_loss_$(p)_band.dat", c.epoch, c.lo, c.hi;
              source = "results/e6_basin_training, point $p", note = "min-max across 3 seeds")
end
writedat("fig1_pts.dat", pts;
         source = "results/e6_basin_training + results/ep_adiabatic/grid.csv",
         note = "acc and w1 at the final epoch, median over 3 seeds; cosmed from the grid cell")

# =====================================================================
# Figure 4 -- spike-timing readout floor
# =====================================================================
println("\nFigure 4:")
rdall = CSV.read(joinpath(RES, "ep_readout_floor", "grid.csv"), DataFrame)
rd = rdall[rdall.project .== "hard", :]
deltas = sort(unique(rd.readout)); epss = sort(unique(rd.eps)); jits = sort(unique(rd.jitter))
colname(d) = "d" * replace(@sprintf("%g", d), "." => "")
# LaTeX macro names cannot contain digits, so the quanta get spelled-out names.
const DWORD = Dict(0.0 => "Zero", 0.005 => "Five", 0.01 => "Ten", 0.02 => "Twenty")
wordname(d) = get(DWORD, round(Float64(d), digits = 4), "Q")

eps_tbl = DataFrame(eps = epss)
for d in deltas
    s = rd[(rd.readout .== d) .& (rd.jitter .== 0), :]
    m = combine(groupby(s, :eps), :cos_l1 => median => :c); sort!(m, :eps)
    eps_tbl[!, colname(d)] = m.c
end
writedat("fig4_eps.dat", eps_tbl;
         source = "results/ep_readout_floor/grid.csv, project=hard, jitter=0",
         note = "columns dN = readout quantum in turns; values are median cos_l1")

dit = DataFrame(jitter = jits)
for d in deltas
    d == 0 && continue      # jitter is a multiple of delta; undefined at delta = 0
    s = rd[(rd.readout .== d) .& (rd.eps .== 0.3), :]
    m = combine(groupby(s, :jitter), :cos_l1 => median => :c,
                :cos_l1 => (v -> quantile(v, 0.25)) => :lo,
                :cos_l1 => (v -> quantile(v, 0.75)) => :hi)
    sort!(m, :jitter)
    dit[!, colname(d)] = m.c
    dit[!, colname(d) * "lo"] = m.lo
    dit[!, colname(d) * "hi"] = m.hi
    writeband("fig4_dither_band_$(colname(d)).dat", m.jitter, m.lo, m.hi;
              source = "results/ep_readout_floor/grid.csv, delta=$d, eps=0.3",
              note = "interquartile over draws")
end
writedat("fig4_dither.dat", dit;
         source = "results/ep_readout_floor/grid.csv, project=hard, eps=0.3",
         note = "jitter in multiples of delta; delta=0 excluded (no quantum to scale against)")

best(d) = maximum(median(rd[(rd.readout .== d) .& (rd.jitter .== 0) .& (rd.eps .== e), :cos_l1]) for e in epss)
macroset!("fig4", "FigRdExact", @sprintf("%.3f", best(0.0)))
for d in deltas
    d == 0 && continue
    bj = maximum(median(rd[(rd.readout .== d) .& (rd.jitter .== j) .& (rd.eps .== 0.3), :cos_l1]) for j in jits)
    macroset!("fig4", "FigRd" * wordname(d), @sprintf("%.3f", best(d)))
    macroset!("fig4", "FigRd" * wordname(d) * "Dith", @sprintf("%.3f", bj))
end
macroset!("fig4", "FigRdSoft", @sprintf("%.3f",
    median(rdall[(rdall.readout .== 0.005) .& (rdall.jitter .== 0) .&
                 (rdall.eps .== 0.3) .& (rdall.project .== "soft"), :cos_l1])))
macroset!("fig4", "FigRdN", string(nrow(rdall)))

# =====================================================================
# Figure 2 -- distortion and recovery
# =====================================================================
println("\nFigure 2:")
ft = CSV.read(joinpath(RES, "ep_analog_finetune", "analog_finetune_ddbaa3d.csv"), DataFrame)

# The sweep has been run more than once and appends, so some (pretrain, type,
# param, rep) keys appear twice -- the SAME damage draw measured against a
# different pretrained network, because BP pretraining is not bit-reproducible
# under multithreaded BLAS. Those are repeated measurements, not independent
# samples: keeping both would inflate n and understate the spread. As found,
# lognormal 0.03 carried 16 rows for 8 draws and lognormal 0.1 carried 9.
let before = nrow(ft)
    unique!(ft, [:pretrain, :impairment_type, :param, :rep])
    before == nrow(ft) ||
        @info "dropped $(before - nrow(ft)) duplicate (pretrain, type, param, rep) rows"
end
ft = ft[ft.pretrain .== "backprop", :]
const SERIES = [(:acc_clean, "clean"), (:acc_bp_ft, "bp"), (:acc_tuned, "ep"),
                (:acc_readout_only, "ro"), (:acc_impaired, "imp")]

# Severity means something different in each map. Three are dimensionless -- a
# log-space sigma for the multiplicative map, a fraction for the two stuck faults
# -- but the additive-Gaussian sigma is an ABSOLUTE standard deviation in weight
# units, so a bare sigma is uninterpretable next to the others. Divide it by the
# RMS weight, measured by the E2_NORMS_ONLY pass, and emit both.
RMSW = let f = joinpath(RES, "e2_norms", "damage_norms_ddbaa3d.csv")
    if isfile(f)
        d = CSV.read(f, DataFrame)
        "rms_clean" in names(d) ? Float64(first(d.rms_clean)) : NaN
    else
        NaN
    end
end
isnan(RMSW) || macroset!("fig2", "FigWrms", @sprintf("%.4f", RMSW))
isnan(RMSW) && @warn "no rms_clean yet -- rerun e2_full_sweep.jl with E2_NORMS_ONLY=1"
for t in sort(unique(ft.impairment_type))
    s = ft[ft.impairment_type .== t, :]
    g = combine(groupby(s, :param), nrow => :n,
        [c => median => Symbol(nm) for (c, nm) in SERIES]...,
        [c => (v -> quantile(v, 0.25)) => Symbol(nm * "lo") for (c, nm) in SERIES]...,
        [c => (v -> quantile(v, 0.75)) => Symbol(nm * "hi") for (c, nm) in SERIES]...)
    sort!(g, :param); rename!(g, :param => :sev)
    # sev_x is the severity the figure plots: sigma/RMS for additive Gaussian,
    # the raw parameter for every other map.
    g.sev_x = t == "gaussian" && !isnan(RMSW) ? g.sev ./ RMSW : copy(g.sev)
    writedat("fig2_rec_$(t).dat", g;
             source = "results/ep_analog_finetune/analog_finetune_$(gitrev_of(ft)).csv, pretrain=backprop",
             note = "median and IQR over $(maximum(g.n)) draws; clean/bp/ep/ro/imp")
end
# The sweep has been extended across several sessions and each invocation
# pretrains afresh; BP pretraining is not bit-reproducible (multithreaded BLAS
# reduction order depends on the thread count), so acc_clean varies slightly
# between runs. Quote the spread, not a single ceiling.
let cl = sort(unique(round.(Float64.(ft.acc_clean), digits = 4)))
    macroset!("fig2", "FigClean", @sprintf("%.3f", median(ft.acc_clean)))
    macroset!("fig2", "FigCleanLo", @sprintf("%.3f", minimum(cl)))
    macroset!("fig2", "FigCleanHi", @sprintf("%.3f", maximum(cl)))
    macroset!("fig2", "FigCleanRuns", string(length(cl)))
end
# Cells with fewer than MINREPS draws are held back from Figure 2(b) -- the same
# threshold the plotting script applies -- so the quoted draw count describes
# what is actually shown. Keep these two in step.
const FIG2_MINREPS = 4
let cnt = combine(groupby(ft, [:impairment_type, :param]), nrow => :n)
    shown = cnt[cnt.n .>= FIG2_MINREPS, :n]
    macroset!("fig2", "FigNdraw",
              minimum(shown) == maximum(shown) ? string(minimum(shown)) :
              string(minimum(shown)) * "--" * string(maximum(shown)))
    macroset!("fig2", "FigNdrawMin", string(minimum(shown)))
    macroset!("fig2", "FigNdrawMax", string(maximum(shown)))
    macroset!("fig2", "FigHeldBack", string(count(<(FIG2_MINREPS), cnt.n)))
end

pf_files = filter(f -> occursin(r"^lockin_paired_.*\.csv$", basename(f)),
                  readdir(joinpath(RES, "ep_analog_finetune"); join = true))
if isempty(pf_files)
    @warn "no lockin_paired_*.csv yet -- Figure 2's agreement panel has no data"
else
    src = last(sort(pf_files))
    pf = CSV.read(src, DataFrame)
    pf.delta = pf.acc_lockin .- pf.acc_static
    tid = Dict(t => i for (i, t) in enumerate(sort(unique(pf.impairment_type))))
    out = DataFrame(static = pf.acc_static, lockin = pf.acc_lockin,
                    tid = [tid[t] for t in pf.impairment_type], imp = pf.acc_impaired,
                    sev = pf.param, delta = pf.delta)
    writedat("fig2_paired.dat", out;
             source = "results/ep_analog_finetune/$(basename(src))",
             note = "paired: identical base network and identical damage draw; tid " *
                    join(("$i=$t" for (t, i) in sort(collect(tid), by = last)), ", "))

    # The grand mean is misleading on its own: the two estimators agree at mild
    # damage and diverge with severity, and almost all of the divergence is one
    # fault type. Emit the per-cell breakdown so the figure can show that.
    cells = combine(groupby(pf, [:impairment_type, :param]),
                    nrow => :n, :delta => mean => :mean,
                    :delta => median => :med,
                    :delta => (v -> length(v) > 1 ? 1.96 * std(v) / sqrt(length(v)) : NaN) => :ci)
    sort!(cells, [:impairment_type, :param])
    cells.tid = [tid[t] for t in cells.impairment_type]
    writedat("fig2_paired_cells.dat", select(cells, :tid, :param, :n, :mean, :med, :ci);
             source = "results/ep_analog_finetune/$(basename(src))",
             note = "mean(lockin - static) per (fault, severity) cell with 95% CI")

    d = pf.delta
    macroset!("fig2", "FigPairDelta", @sprintf("%+.3f", mean(d)))
    macroset!("fig2", "FigPairCI", @sprintf("%.3f", 1.96 * std(d) / sqrt(length(d))))
    macroset!("fig2", "FigPairN", string(length(d)))
    macroset!("fig2", "FigPairWins", string(count(>(0), d)))
    # the two extremes of the breakdown, which are what the panel is really about
    worstcell = cells[argmin(cells.mean), :]
    bestcell  = cells[argmax(cells.mean), :]
    macroset!("fig2", "FigPairWorst", @sprintf("%+.3f", worstcell.mean))
    macroset!("fig2", "FigPairWorstCell",
              "$(replace(worstcell.impairment_type, "_" => "\\_")) $(worstcell.param)")
    macroset!("fig2", "FigPairBest", @sprintf("%+.3f", bestcell.mean))
    macroset!("fig2", "FigPairBestCell",
              "$(replace(bestcell.impairment_type, "_" => "\\_")) $(bestcell.param)")
    mild = cells[cells.n .> 0 .&& abs.(cells.mean) .< 0.025, :]
    macroset!("fig2", "FigPairAgreeN", string(nrow(mild)))
    macroset!("fig2", "FigPairCellN", string(nrow(cells)))
end

# =====================================================================
# Figure 3 -- three-factor correspondence
# =====================================================================
println("\nFigure 3:")
e4 = CSV.read(joinpath(RES, "e4_three_factor_scale", "e4_three_factor_ddbaa3d.csv"), DataFrame)
macroset!("fig3", "FigTfCosMin", @sprintf("%.6f", minimum(e4.cos_lk_3f)))
macroset!("fig3", "FigTfErrLo", @sprintf("%.0e", minimum(e4.rel_err_lk_3f)))
macroset!("fig3", "FigTfErrHi", @sprintf("%.0e", maximum(e4.rel_err_lk_3f)))
macroset!("fig3", "FigTfNin", string(length(unique(e4.input_idx))))

e1 = CSV.read(joinpath(RES, "ep_trained_vs_rescaled", "trained_vs_rescaled.csv"), DataFrame)
e1 = e1[(e1.tag .== "trained") .& (e1.estimator .== "lockin") .& (e1.fd_trusted .== true), :]
macroset!("fig3", "FigLiepFdErr", @sprintf("%.3f", median(skipmissing(e1.relerr_fd))))

pairs_files = filter(f -> occursin(r"^update_pairs_.*\.csv$", basename(f)),
                     isdir(joinpath(RES, "e4_three_factor_scale")) ?
                     readdir(joinpath(RES, "e4_three_factor_scale"); join = true) : String[])
if isempty(pairs_files)
    @warn "no update_pairs_*.csv yet -- run scripts/e4_export_update_pairs.jl"
else
    src = last(sort(pairs_files))
    pp = CSV.read(src, DataFrame)
    # The figure is rendered by Plotly rather than pgfplots, so TeX's main-memory
    # ceiling on scatter marks no longer applies and every measured pair is drawn.
    nkeep = typemax(Int)
    if nrow(pp) > nkeep
        idx = sort(shuffle(MersenneTwister(20260908), 1:nrow(pp))[1:nkeep])
        pp_plot = pp[idx, :]
    else
        pp_plot = pp
    end
    writedat("fig3_pairs.dat", pp_plot;
             source = "results/e4_three_factor_scale/$(basename(src))",
             note = "component-wise (lock-in, three-factor) update pairs; " *
                    "$(nrow(pp_plot)) of $(nrow(pp)) measured pairs, thinned for plotting")
    macroset!("fig3", "FigTfNpair", string(nrow(pp)))
    macroset!("fig3", "FigTfNplot", string(nrow(pp_plot)))
end

println()
write_macros()
println("\n=== done ===")
