module PhasorNetworks

export 
#types
SpikeTrain, 
CoupledChain,
CoupledLayerOutput, 
SpikeTrainGPU,
MakeSpiking,
LocalCurrent,
SpikingArgs, 
SpikingCall, 
CurrentCall,
SpikingArgs_NN,
TrackOutput,
SolutionType,
PhaseSolution,
PotentialSolution,
SpikingSolution,
CurrentSolution,
Phase,
Args,

#domain conversions
phase_to_train,
phase_to_potential,
phase_to_current,
solution_to_potential,
solution_to_phase,
solution_to_train,
potential_to_phase,
train_to_phase,
time_to_phase,
phase_to_time,
potential_to_time,
time_to_potential,
bias_to_complex_offset,
kernel_integral,
arc_error,
cmpx_to_realvec,
realvec_to_cmpx,
period_to_angfreq,
angfreq_to_period,
normalize_to_unit_circle,
soft_normalize_to_unit_circle,
periodic_von_mises_kernel,
complex_von_mises_kernel,

#spiking
default_spk_args,
count_nans,
zero_nans,
stack_trains,
vcat_trains,
delay_train,
match_offsets,
mean_phase,
end_phase,
oscillator_bank,
neuron_constant,
get_time,

#vsa
v_bundle,
v_bundle_project,
v_bind,
v_unbind,
angle_to_complex,
chance_level,
complex_to_angle,
random_symbols,
similarity,
similarity_self,
similarity_outer,
similarity_loss,
codebook_loss,

#ssm
PhasorSSM,
SSMReadout,
phasor_kernel,
causal_conv,
causal_conv_fft,
dirac_encode,
causal_conv_dirac,
hippo_legs_diagonal,
psk_encode,
impulse_encode,
SSMCrossAttention,
SSMSelfAttention,
MakeSpikingSSM,
ssm_phases_to_train,
ssm_extract_phases,
reconstruct_from_current,

#network
attend,
solve_coupled,
get_layer_potential,
get_layer_phase,
variance_scaling,
dense_onehot,
Codebook,
ComplexBias,
PhasorConv,
PhasorDense,
PhasorSTFT,
PhasorFixed,
MinPool,
ResidualBlock,
PhasorAttention,
SingleHeadAttention,
train,
soft_angle,
default_bias,
zero_bias,

#metrics
arc_error,
angular_mean,
exp_score,
z_score,
similarity_correlation,
cycle_correlation,
cycle_sparsity,
cor_realvals,
predict,
evaluate_loss,
evaluate_accuracy,
loss_and_accuracy,
spiking_loss_and_accuracy,
confusion_matrix,
OvR_matrices,
tpr_fpr,
interpolate_roc

include("imports.jl")
include("constants.jl")
include("types.jl")
include("domains.jl")
include("gpu.jl")
include("spiking.jl")
include("vsa.jl")
include("kernels.jl")
include("network.jl")
include("ssm.jl")
include("metrics.jl")

end
