module PhasorNetworks

export
#types
SpikeTrain,
SpikeTrainGPU,
MakeSpiking,
LocalCurrent,
SpikingArgs,
SpikingCall,
CurrentCall,
TrackOutput,
SolutionType,
PhaseSolution,
PotentialSolution,
SpikingSolution,
CurrentSolution,
Phase,
Args,

#domain conversions
phase_to_train,
phase_to_potential,
phase_to_current,
solution_to_potential,
solution_to_phase,
solution_to_train,
potential_to_phase,
train_to_phase,
time_to_phase,
phase_to_time,
potential_to_time,
unrotate_solution,
time_to_potential,
bias_to_complex_offset,
kernel_integral,
arc_error,
cmpx_to_realvec,
realvec_to_cmpx,
period_to_angfreq,
angfreq_to_period,
normalize_to_unit_circle,
soft_normalize_to_unit_circle,
complex_von_mises_kernel,

#spiking
default_spk_args,
count_nans,
zero_nans,
stack_trains,
vcat_trains,
delay_train,
match_offsets,
mean_phase,
end_phase,
oscillator_bank,
neuron_constant,
get_time,

#vsa
v_bundle,
v_bind,
v_unbind,
angle_to_complex,
chance_level,
complex_to_angle,
random_symbols,
orthogonal_codes,
similarity,
similarity_self,
similarity_outer,
similarity_outer_heads,
similarity_loss,
codebook_loss,

#ssm
SSMReadout,
phasor_kernel,
causal_conv,
causal_conv_fft,
dirac_encode,
causal_conv_dirac,
hippo_legs_diagonal,
psk_encode,
impulse_encode,
SSMCrossAttention,
SSMSelfAttention,
PhasorLSA,
PhasorLCA,
PhaseRecenter,
PhasorResidual,
PhasorTransformerBlock,
MakeSpikingSSM,
ssm_phases_to_train,
sample_phases_at_periods,
reconstruct_from_current,

#backend
select_device,

#network
attend,
variance_scaling,
dense_onehot,
Codebook,
ComplexBias,
PhasorConv,
PhasorDense,
MultiModePhasorDense,
PhasorResonant,
ResonantSTFT,
waveform_currentcall,
PhasorFixed,
MinPool,
ResidualBlock,
PhasorAttention,
SingleHeadAttention,
AttractorPhasorSSM,
attractor_pull,
PhasorWaveSheet,
wave_simulate,
SolitonWaveSheet,
soliton_simulate,
dispersion,
dispersion_diagnostics,
spectral_occupancy,
transport_forecast,
zero_gvd_speed,
radial_band,
wave_transport,
matched_conduction_speed,
emission_threshold,
wave_homeostat_trace,
ExcitableWaveSheet,
excitable_simulate,
excitable_emit,
excitable_regime,
front_speed,
moe_gate,
update_moe_bias,
WaveExpertSheet,
route_stats,
PhasorVelocityBank,
velocity_coupling,
velocity_bank_run,
channel_velocities,
decode_velocity,
moving_drive,
hardware_bank,
detector_noise,
velocity_bank_run_disordered,
delay_line_length,
kappa_from_dt,
dt_from_kappa,
speed_from_dt,
dt_from_speed,
nyquist_dt,
train,
soft_angle,
default_bias,
zero_bias,

#hep
holotanh,
holotanh_deriv,
hep_energy,
hep_equilibrium,
hep_gradient,
hep_train,
hep_cost_xent,
hep_cost_xent_grad,
HolomorphicReadout,
hep_interference_cost,

#ep
SimilarityCost,
CodebookCost,
StaticEP,
LockinEP,
phasor_settle,
ep_gradient,
ep_train,
ep_loss,
fd_gradient_phasor,
codebook_logits,
ep_predict,
chain_hebbians,

#metrics
arc_error,
angular_mean,
exp_score,
z_score,
similarity_correlation,
cycle_correlation,
cycle_arc_error,
cycle_sparsity,
cor_realvals,
predict,
evaluate_loss,
evaluate_accuracy,
loss_and_accuracy,
spiking_loss_and_accuracy,
confusion_matrix,
OvR_matrices,
tpr_fpr,
interpolate_roc,

#datasets
fashion_mnist_data

include("imports.jl")
include("constants.jl")
include("types.jl")
include("backend.jl")
include("domains.jl")
include("activations.jl")
include("gpu.jl")
include("spiking.jl")
include("vsa.jl")
include("kernels.jl")
include("network.jl")
include("ssm.jl")
include("attractor_ssm.jl")
include("wave.jl")
include("excitable.jl")
include("velocity_bank.jl")
include("velocity_bank_hw.jl")
include("metrics.jl")
include("datasets.jl")
include("hep.jl")
include("ep.jl")

end
